package org.example.h2.enums;

import lombok.Getter;

/**
 * 作者：忘月沁 https://www.bilibili.com/read/cv13055247/ 出处：bilibili
 * https://github.com/OrdinaryRoad-Project/ordinaryroad-live-chat-client/blob/main/live-chat-client-codec/live-chat-client-codec-bilibili/src/main/java/tech/ordinaryroad/live/chat/client/codec/bilibili/constant/BilibiliCmdEnum.java
 */
@Getter
public enum DanmukEnum {

    ACTIVITY_BANNER_CHANGE("待更新"),
    ACTIVITY_BANNER_CHANGE_V2("待更新"),
    ANCHOR_LOTTERY_ACTIVITY("待更新"),
    ANCHOR_LOT_AWARD("天选时刻中奖信息"),
    ANCHOR_LOT_CHECKSTATUS("天选时刻检查状态"),
    ANCHOR_LOT_END("天选时刻结束"),
    ANCHOR_LOT_START("天选时刻开始"),
    ANCHOR_NORMAL_NOTIFY("天选时刻一般通知"),
    AREA_RANK_CHANGED("分区榜单更新"),
    BENEFIT_CARD_CLEAN("待更新"),
    BOX_ACTIVITY_START("待更新"),
    CARD_MSG("卡片消息"),
    CHG_RANK_REFRESH("充电榜单更新"),
    COMBO_SEND("礼物连击"),
    COMMON_ANIMATION("公共动画"),
    COMMON_NOTICE_DANMAKU("公共弹幕通知"),
    CUSTOM_NOTICE_CARD("用户通知卡片"),
    CUT_OFF("待更新"),
    DANMU_AGGREGATION("弹幕聚合"),
    DANMU_MSG("弹幕消息"),
    DANMU_TAG_CHANGE("待更新"),
    DM_INTERACTION("他们都在说"),
    ENTRY_EFFECT("用户入场信息"),
    ENTRY_EFFECT_MUST_RECEIVE("用户入场信息（提示回应）"),
    FULL_SCREEN_SPECIAL_EFFECT("全屏特效"),
    FUNCTION_CARD("互动卡片"),
    GIFT_PANEL_PLAN("礼物计划面板"),
    GIFT_STAR_PROCESS("礼物处理开始"),
    GOTO_BUY_FLOW("去购买"),
    GUARD_ACHIEVEMENT_ROOM("待更新"),
    GUARD_BUY("购买舰长（开通舰长）"),
    GUARD_HONOR_THOUSAND("守卫荣誉千舰"),
    HOT_BUY_NUM("待更新"),
    HOT_RANK_CHANGED("主播实时活动排名"),
    HOT_RANK_CHANGED_V2("热榜更新"),
    HOT_RANK_SETTLEMENT("热榜"),
    HOT_RANK_SETTLEMENT_V2("热榜"),
    HOT_ROOM_NOTIFY("热门直播间通知"),
    INTERACTIVE_USER("待更新"),
    INTERACT_WORD("直播间进场提示"),
    LIKE_GUIDE_USER("直播间用户点赞引导"),
    LIKE_INFO_V3_CLICK("直播间用户点赞V3"),
    LIKE_INFO_V3_NOTICE("直播间用户点赞引导V3"),
    LIKE_INFO_V3_UPDATE("直播间点赞数更新V3"),
    LIKE_SO_HOT("待更新"),
    LIVE("开播通知"),
    LIVE_ANI_RES_UPDATE("直播动态资源更新"),
    LIVE_INTERACTIVE_GAME("互动游戏"),
    LIVE_INTERACT_GAME_STATE_CHANGE("直播互动游戏舞台更新"),
    LIVE_MULTI_VIEW_NEW_INFO("更多解说信息"),
    LIVE_OPEN_PLATFORM_GAME("直播开放平台互通游戏开启"),
    LIVE_PANEL_CHANGE_CONTENT("直播面板内容更新"),
    LOG_IN_NOTICE("登录提示"),
    LPL_REALTIME_STATUS_CHANGED("待更新"),
    NOTICE_MSG("直播通知消息"),
    ONLINE_RANK_COUNT("在线排行榜统计"),
    ONLINE_RANK_TOP3("在线排行榜统计"),
    ONLINE_RANK_V2("在线排行榜V2"),
    PANEL_INTERACTIVE_NOTIFY_CHANGE("待更新"),
    PK_BATTLE_END("战斗对决结束"),
    PK_BATTLE_ENTRANCE("PK战斗入口"),
    PK_BATTLE_FINAL_PROCESS("战斗对接最终处理"),
    PK_BATTLE_MULTIPLE_AWARD("战斗对决加倍奖励"),
    PK_BATTLE_MULTIPLE_BEGIN("战斗对决加倍开始"),
    PK_BATTLE_MULTIPLE_DRAW_RES("战斗对决加倍绘制资源"),
    PK_BATTLE_MULTIPLE_RES("战斗对决加倍资源"),
    PK_BATTLE_PRE("战斗对决预览"),
    PK_BATTLE_PRE_NEW("战斗对决预览新"),
    PK_BATTLE_PROCESS("战斗对决处理"),
    PK_BATTLE_PROCESS_NEW("战斗对决处理新"),
    PK_BATTLE_RANK_CHANGE("待更新"),
    PK_BATTLE_SETTLE("待更新"),
    PK_BATTLE_SETTLE_USER("待更新"),
    PK_BATTLE_SETTLE_V2("待更新"),
    PK_BATTLE_START("战斗对决开始"),
    PK_BATTLE_START_NEW("战斗对决开始"),
    PK_BATTLE_VIDEO_PUNISH_BEGIN("战斗对决视频惩罚开始"),
    PK_BATTLE_VIDEO_PUNISH_END("战斗对决视频惩罚结束"),
    PLAY_TAG("播放标签图标"),
    POPULARITY_RANK_TAB_CHG("直播人气榜页签更新"),
    POPULARITY_RED_POCKET_NEW("人气榜红包礼物新"),
    POPULARITY_RED_POCKET_START("人气榜红包礼物抽奖开始"),
    POPULARITY_RED_POCKET_V2_NEW("人气榜红包礼物V2新"),
    POPULARITY_RED_POCKET_V2_START("人气榜红包礼物抽奖V2开始"),
    POPULARITY_RED_POCKET_V2_WINNER_LIST("人气榜红包V2中奖名单"),
    POPULARITY_RED_POCKET_WINNER_LIST("人气红包中奖名单"),
    POPULAR_RANK_CHANGED("直播人气榜更新"),
    POPULAR_RANK_GUIDE_CARD("直播人气榜引导卡片"),
    PREPARING("直播准备中"),
    RANK_CHANGED("排行榜更新"),
    RANK_REM("排行榜更新"),
    RECOMMEND_CARD("直播推荐卡片"),
    REENTER_LIVE_ROOM("待更新"),
    REVENUE_RANK_CHANGED("主营业务收入排行变更"),
    RING_STATUS_CHANGE("振铃状态更新"),
    RING_STATUS_CHANGE_V2("振铃状态更新V2"),
    ROOM_ADMINS("待更新"),
    ROOM_BLOCK_MSG("直播间封禁消息"),
    ROOM_CHANGE("直播间信息更新"),
    ROOM_REAL_TIME_MESSAGE_UPDATE("直播间实时信息更新"),
    ROOM_SILENT_OFF("直播间关闭禁言"),
    ROOM_SILENT_ON("直播间开启禁言"),
    ROOM_SKIN_MSG("直播间皮肤信息"),
    SEND_GIFT("礼物投喂"),
    SEND_GIFT_V2("礼物投喂V2"),
    SHOPPING_BUBBLES_STYLE("待更新"),
    SHOPPING_CART_SHOW("购物车展示"),
    SHOPPING_EXPLAIN_CARD("待更新"),
    SPECIAL_GIFT("待更新"),
    STOP_LIVE_ROOM_LIST("停播直播房间号列表"),
    SUPER_CHAT_ENTRANCE("醒目留言入场"),
    SUPER_CHAT_MESSAGE("醒目留言"),
    SUPER_CHAT_MESSAGE_DELETE("醒目留言删除"),
    SUPER_CHAT_MESSAGE_JPN("醒目留言（日文）"),
    SYS_MSG("系统消息"),
    TRADING_SCORE("交易评分"),
    USER_TOAST_MSG("用户提示消息"),
    USER_TOAST_MSG_V2("用户提示消息V2"),
    VIDEO_CONNECTION_JOIN_END("视频连线结束"),
    VIDEO_CONNECTION_MSG("视频连线消息"),
    VOICE_CHAT_UPDATE("待更新"),
    VOICE_JOIN_LIST("直播间连麦加入列表"),
    VOICE_JOIN_ROOM_COUNT_INFO("直播间连麦加入计数"),
    VOICE_JOIN_STATUS("直播间连麦加入状态"),
    VOICE_JOIN_SWITCH("连麦切换"),
    WARNING("待更新"),
    WATCHED_CHANGE("直播间观看人数更新"),
    WELCOME("欢迎加入房间"),
    WELCOME_GUARD("欢迎荣耀舰长加入直播间"),
    WIDGET_BANNER("海报组件"),
    WIDGET_GIFT_STAR_PROCESS("礼物组件处理开始"),
    WIDGET_WISH_INFO("待更新"),
    WIN_ACTIVITY("待更新"),
//    ROOM_NEWS_UPDATE("待更新"),
//    RECALL_DANMU_MSG("待更新"),
//    ANCHOR_LOT_NOTICE("待更新"),
//    OTHER_SLICE_LOADING_RESULT("待更新"),
    _UN_KNOW_CMD_NEED_AFTER_ADD("未知弹幕归档"),
    room_admin_entrance("待更新"),

    ;

    String desc;

    DanmukEnum(String desc) {
        this.desc = desc;
    }
}
