
DROP TABLE IF EXISTS LOAN_SYS_DANMUK CASCADE CONSTRAINTS;

/*==============================================================*/
/* Table: LOAN_SYS_DANMUK                                          */
/*==============================================================*/
CREATE TABLE LOAN_SYS_DANMUK
(
   ID                   VARCHAR(64)          NOT NULL,
   ROOM_ID                   VARCHAR(64),
   DANMUK     CLOB,
   DANMUK_MSG          CLOB,
   DANMUK_TYPE          VARCHAR(400),
   DANMUK_USER_ID          VARCHAR(400),
   DANMUK_USER_NAME          VARCHAR(400),
   DANMUK_TIME          TIMESTAMP(9),
   CONSTRAINT "PK_DANMUK" PRIMARY KEY (ID)
);

COMMENT ON TABLE LOAN_SYS_DANMUK IS
'系统管理_弹幕表';

COMMENT ON COLUMN LOAN_SYS_DANMUK.ID IS
'主键';

COMMENT ON COLUMN LOAN_SYS_DANMUK.ROOM_ID IS
'房间号';

COMMENT ON COLUMN LOAN_SYS_DANMUK.DANMUK IS
'弹幕数据';

COMMENT ON COLUMN LOAN_SYS_DANMUK.DANMUK_MSG IS
'弹幕消息';

COMMENT ON COLUMN LOAN_SYS_DANMUK.DANMUK_TYPE IS
'弹幕类型';

COMMENT ON COLUMN LOAN_SYS_DANMUK.DANMUK_USER_ID IS
'弹幕用户Id';

COMMENT ON COLUMN LOAN_SYS_DANMUK.DANMUK_USER_NAME IS
'弹幕用户名称';

COMMENT ON COLUMN LOAN_SYS_DANMUK.DANMUK_TIME IS
'弹幕时间';

DROP TABLE IF EXISTS DANMUK_ORIGIN;
CREATE TABLE DANMUK_ORIGIN(
    ID VARCHAR(32) NOT NULL,
    BATCH_NO VARCHAR(255),
    ROOM_ID VARCHAR(255),
    ORIGIN_FILE VARCHAR(255),
    ORIGIN_SER NUMBER,
    COMMAND VARCHAR(255),
    ORIGIN_CONTENT CLOB,
    CREATE_TIME TIMESTAMP,
    CONSTRAINT "DANMUK_ORIGIN_KEY_ID" PRIMARY KEY (ID)
);

COMMENT ON TABLE DANMUK_ORIGIN IS 'DANMUK_ORIGIN';
COMMENT ON COLUMN DANMUK_ORIGIN.ID IS '标识';
COMMENT ON COLUMN DANMUK_ORIGIN.BATCH_NO IS '批次号';
COMMENT ON COLUMN DANMUK_ORIGIN.ROOM_ID IS '直播房间号';
COMMENT ON COLUMN DANMUK_ORIGIN.ORIGIN_FILE IS '数据来源';
COMMENT ON COLUMN DANMUK_ORIGIN.ORIGIN_SER IS '数据来源序号';
COMMENT ON COLUMN DANMUK_ORIGIN.COMMAND IS '指令';
COMMENT ON COLUMN DANMUK_ORIGIN.ORIGIN_CONTENT IS '数据内容';
COMMENT ON COLUMN DANMUK_ORIGIN.CREATE_TIME IS '创建时间';

DROP TABLE IF EXISTS DANMUK_EXART;
CREATE TABLE DANMUK_EXART(
    ID VARCHAR(32) NOT NULL,
    REF_ID VARCHAR(255),
    SPEC_OUTER_CONTAINER_TYPE VARCHAR(255),
    SPEC_LEVEL NUMBER,
    SPEC_LEVEL_NAME VARCHAR(255),
    SPEC_FILED VARCHAR(255),
    SPEC_VAL_SER NUMBER,
    SPEC_VAL_TYPE VARCHAR(255),
    SPEC_VAL CLOB,
    CREATE_TIME TIMESTAMP,
    CONSTRAINT "DANMUK_EXART_KEY_ID" PRIMARY KEY (ID)
);

COMMENT ON TABLE DANMUK_EXART IS 'DANMUK_EXART';
COMMENT ON COLUMN DANMUK_EXART.ID IS '标识';
COMMENT ON COLUMN DANMUK_EXART.REF_ID IS '引用标识';
COMMENT ON COLUMN DANMUK_EXART.SPEC_OUTER_CONTAINER_TYPE IS '特征所在容器类型';
COMMENT ON COLUMN DANMUK_EXART.SPEC_LEVEL IS '特征层级';
COMMENT ON COLUMN DANMUK_EXART.SPEC_LEVEL_NAME IS '特征层级名';
COMMENT ON COLUMN DANMUK_EXART.SPEC_FILED IS '特征标签';
COMMENT ON COLUMN DANMUK_EXART.SPEC_VAL_SER IS '特征值序号';
COMMENT ON COLUMN DANMUK_EXART.SPEC_VAL_TYPE IS '特征值类型';
COMMENT ON COLUMN DANMUK_EXART.SPEC_VAL IS '特征值';
COMMENT ON COLUMN DANMUK_EXART.CREATE_TIME IS '创建时间';
